M48
; DRILL file KiCad 10.0.1 date 2026-09-02T21:13:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-02T21:13:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.048
%
G90
G05
T1
X118.613Y-67.973
X148.413Y-67.973
T2
X158.233Y-90.533
X158.26Y-78.533
M30
